// default constants from supra-l1-sdk
export const DEFAULT_MAX_GAS_UNITS = 500000
export const DEFAULT_GAS_PRICE = 100
export const MILLISECONDS_PER_SECOND = 1000
export const DEFAULT_TX_EXPIRATION_DURATION = 300
export const MAX_RETRY_FOR_TRANSACTION_COMPLETION = 300
export const DELAY_BETWEEN_POOLING_REQUEST = 1000
